### ISSUE TITLE
Question: Why use `os.sep()`?

### ISSUE THREAD

**Issue by MrGallo** [ICS2O-Gallo/10c-cpt-timothy-and-nicholas#1]
Why are you using `os.sep()` rather than `/`?

**Yours:**
https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/blob/0798b8a2398b76b84fcbe3905072af25ef8be2da/Plane_Game_Beta.py#L10-L11

**Proper way (?):**
```python
title_text = arcade.load_texture('assets/text/title.png', 0, 0, 505, 150) 
```

**Comment by nicholaspoon03** [comment]
Good question. It has been changed
