### ISSUE TITLE
Implement Sprites

### ISSUE THREAD

**Issue by MrGallo** [ICS2O-Gallo/10c-cpt-timothy-and-nicholas#3]
I suggest transitioning to using `arcade.Sprite` for your game objects. Arcade has some optimization when drawing sprites so it doesn't slow down the game so much.

http://arcade.academy/examples/index.html#sprites

**Comment by Ti1mmy** [comment]
[f4cd3c9](https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/commit/094be4516698d9b2cd060b81b04ede273dbc2268#diff-c8ee6819a4a8fb07bd52fc5a2556bb7c)

Game objects have been changed to sprites, barring images that are used more than once or use a fair bit of image manipulation that image.sprite() can't offer.

All assets that may effect actual game performance have been transferred to sprites.

**Comment by MrGallo** [comment]
Sprites should be created **only once**, globally. It appears, you create sprites every time you need to draw them. When you have to move a sprite, use `sprite.center_y += 5` or something.

**Comment by Ti1mmy** [comment]
All sprites have been moved, barring coins, which will have to be added to a list, popped and appended when off the screen or collides with jet.
https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/blob/8e33c2e5fa2a57397541598f3e5008d7bc75554b/Plane_Game_Beta.py#L535-L538

https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/blob/8e33c2e5fa2a57397541598f3e5008d7bc75554b/Plane_Game_Beta.py#L697-L701
