### ISSUE TITLE
Trying to remove redundant variables

### ISSUE THREAD

**Issue by nicholaspoon03** [ICS2O-Gallo/10c-cpt-timothy-and-nicholas#4]
```python
def on_mouse_motion(x, y, dx, dy):
    global mouse_x, mouse_y
    mouse_x = x
    mouse_y = y
```
Is `mouse_x = x` AND `mouse_y = y` necessary

**Comment by Ti1mmy** [comment]
We can change it into a list, but honestly `mouse_x` and `mouse_y` would be easier. Feel free to do like `mouse_pos[0]` for `mouse_x` and `mouse_pos[1]` for `mouse_y` though. 

Your job now ^_^ @nicholaspoon03

**Comment by Ti1mmy** [comment]
Creates more lines than it saves, negligible memory optimization
