### ISSUE TITLE
Anti-Cheat?

### ISSUE THREAD

**Issue by Ti1mmy** [ICS2O-Gallo/10c-cpt-timothy-and-nicholas#6]
What can we do to stop players from just changing values in the .txt files?

**Comment by Ti1mmy** [comment]
Options:
- Checksum
- Hashing the file

**Comment by Ti1mmy** [comment]
[9e53d7c](https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/commit/9e53d7c67cdd5a41accd5048ddd5914a4e4e2850)

[e84311c](https://github.com/ICS2O-Gallo/10c-cpt-timothy-and-nicholas/commit/e84311ca199f52e77c8e4b66ecff103095d701f4)

Shop info is now hashed in the text file, making it very difficult to cheat for people knowledgeable of hashing when given access to the source code (at that point, there are worse things people who are experienced can do other than just cheat in some extra coins to be fair), or outright impossible for those without access to the source code. Any tampering to the file without specifically changing the hash to match, or vice-versa will cause the program to recognize that the file has been changed by an external source.

**TODO:**

- Add repercussions for cheating in the game (Resetting stats maybe?)

**Comment by MrGallo** [comment]
LOL. First students to even care about this in a CPT. Nice thinking. Can I get a quick (2 min) video demo of how it works?
